INSERT INTO USUARIOS (NAME, BIRTHDATE) VALUES ('FRANCISCO', PARSEDATETIME('18/04/1992', 'dd/MM/yyyy'))
INSERT INTO USUARIOS (NAME, BIRTHDATE) VALUES ('JAVIER', PARSEDATETIME('05/01/1990', 'dd/MM/yyyy'))
INSERT INTO USUARIOS (NAME, BIRTHDATE) VALUES ('ANTONIO', PARSEDATETIME('08/08/1991', 'dd/MM/yyyy'))
INSERT INTO USUARIOS (NAME, BIRTHDATE) VALUES ('OSCAR', PARSEDATETIME('12/07/1992', 'dd/MM/yyyy'))
INSERT INTO USUARIOS (NAME, BIRTHDATE) VALUES ('LUCAS', PARSEDATETIME('18/12/1993', 'dd/MM/yyyy'))



